networks:
  lendmate-net:
    external: true

services:
  api-gateway:
    image: "api-gateway"
    build: .
    container_name: api-gateway
    restart: unless-stopped
    networks:
      - lendmate-net
    environment:
      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=60.0 
        -XX:+UseSerialGC 
        -Xss256k 
        -XX:MaxMetaspaceSize=100m
    mem_limit: 300m