networks:
  lendmate-net:
    external: true

services:
  api-gateway:
    image: "api-gateway"
    build: .
    container_name: api-gateway
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - lendmate-net