networks:
  lendmate-net:
    external: true

services:
  api-gateway:
    image: "api-gateway"
    build: .
    container_name: api-gateway
    restart: unless-stopped
    networks:
      - lendmate-net
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: 5367566859703373367639792F423F452848284D6251655468576D5A71347437
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: api-gateway
      CONFIG_SERVER_URL: http://config-server:8888
      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=60.0 
        -XX:+UseSerialGC 
        -Xss256k 
        -XX:MaxMetaspaceSize=256m
    mem_limit: 300m