spring:
  application:
    name: api-gateway
  profiles:
    active: ${ACTIVE_PROFILE:dev}

server:
  port: 8084

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

---
spring:
  config:
    activate:
      on-profile: stage
    import: "configserver:${CONFIG_SERVER_URL}"
